
export const lines = require('./nodes.png')
export const polygon = require('./polygon.png')
export const points = require('./points.png')
export const rectangle = require('./rectangular.png')
export const circle = require('./circle.png')
export const createLayer = require('./add.png')
export const statistics =require('./sigma.png')
export const zoomIn = require('./zoom-in.png')
export const table = require('./edit-table.png')
export const exportFile = require('./export.png')
export const deleteIcon = require('./bin.png')